### ISSUE TITLE
I Can Send Empty file which throws an exception

### ISSUE THREAD

**Issue by Geraldsonp** [alkemyTech/OT300-server#104]
https://github.com/alkemyTech/OT300-server/blob/46e57cec89f19467c6a987a4fdb4aebefb5aa870/OngProject/Controllers/CategoryController.cs#L54

![image](https://user-images.githubusercontent.com/31606909/193379013-b15a0157-c108-441b-a590-6dcf0d290860.png)

**Comment by DnTo** [comment]
On PR #106
